participants:
  - el_type: bor
    cl_type: heimdall
    el_log_level: info
    cl_log_level: debug
  - el_type: erigon
    # el_image: erigontech/erigon:v2.60.10
    cl_type: heimdall
    count: 1

network_params:
  # network: kurtosis
  network_id: 5555

additional_services: [
  "tx_spammer",
]

# count: a
